from pathlib import Path

import tree_sitter_cpp
from tree_sitter import Language, Parser

from modified_cognitive_complexity import cognitive_complexity


def cognitive_complexity_for_file(
    file: Path,
    *,
    goto_nesting: bool = True,
    structural_gotos: bool = False
) -> dict[bytes | None, int]:
    """
    Calculate the modified cognitive complexity of control flow structures in a syntax tree.

    This function traverses a syntax tree generated by Tree-sitter and collects metrics 
    related to control flow structures such as if/else statements, loops, switch cases, 
    conditional expressions, and goto statements. The result is a dictionary, which maps 
    function names to the modified cognitive complexity score. 
    The top-level modified cognitive complexity score is mapped to the 'None' key.
    
    :param file: A Path from which the source code is read.
    :param goto_nesting: If the additional nesting penalty imposed by gotos should be applied.
    :param structural_gotos: A flag specifying if goto statements should inherit a nesting penalty
        by their respective label.

    :return: A mapping from each function name to its score. The score of top-level constructs
        is mapped to the 'None' key.
    """
    
    code = file.read_bytes()
    return cognitive_complexity_for_string(code, goto_nesting=goto_nesting, structural_gotos=structural_gotos)


def cognitive_complexity_for_string(
    code: str | bytes | bytearray | memoryview,
    *,
    goto_nesting: bool = True,
    structural_gotos: bool = False
) -> dict[bytes | None, int]:
    """
    Calculate the modified cognitive complexity of control flow structures in a syntax tree.

    This function traverses a syntax tree generated by Tree-sitter and collects metrics 
    related to control flow structures such as if/else statements, loops, switch cases, 
    conditional expressions, and goto statements. The result is a dictionary, which maps 
    function names to the modified cognitive complexity score. 
    The top-level modified cognitive complexity score is mapped to the 'None' key.
    
    :param code: The source code.
    :param goto_nesting: If the additional nesting penalty imposed by gotos should be applied.
    :param structural_gotos: A flag specifying if goto statements should inherit a nesting penalty
        by their respective label.

    :return: A mapping from each function name to its score. The score of top-level constructs
        is mapped to the 'None' key.
    """
    
    if isinstance(code, str):
        code = code.encode()
    
    lang = Language(tree_sitter_cpp.language())
    parser = Parser(lang)
    tree = parser.parse(code)

    scores_by_function = cognitive_complexity(tree.walk(), goto_nesting=goto_nesting, structural_gotos=structural_gotos)
    return {
        function_name: sum(cost.total for _, cost in scores)
        for function_name, scores
        in scores_by_function.items()
    }